### PR TITLE
Configuring a release plan for trustification

### PR DESCRIPTION
**Pull request by ShakedAviv50313**
Configuring a release plan for Trusted Content - trustification

### CODE REVIEW

**Comment by ShakedAviv50313** [comment]
@gbenhaim Please have a look when you get the chance

**Comment by ShakedAviv50313** [comment]
Hi @scoheb if you have some time please have a look at this PR.
Thanks!

**Comment by ShakedAviv50313** [comment]
@gbenhaim Can you please have another look?
I'm not sure what needs to be changed to fit the new format

**Comment by scoheb** [comment]
First, you need to rebase from main.
Secondly, you can base yourself off of https://github.com/redhat-appstudio/tenants-config/blob/main/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/rh-trex-tenant-rpa.yaml

**Pull request closed without merging**
