### PR TITLE
feat(STONEINTG-696): add integration-service application

### PR DESCRIPTION
**Pull request by hongweiliu17**
Add integration-service application https://github.com/redhat-appstudio/integration-service
1. add IntegrationTestScneario for integration-service
2. add releasePlan for integration-service for integration-service
3. add releasePlanAdmission for integration-service

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Comment by scoheb** [comment]
is this ready to be merged?

**Comment by hongweiliu17** [comment]
We are meeting issue [RHTAPBUGS-1065](https://issues.redhat.com/browse/RHTAPBUGS-1065) and the same issue is being discussed in https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1702373124818979

**Comment by hongweiliu17** [comment]
@scoheb Could you help review and merge this PR when we are waiting for [RHTAPBUGS-1064](https://issues.redhat.com/browse/RHTAPBUGS-1064) to be fixed? Thanks! cc @dirgim

**Comment by hongweiliu17** [comment]
> [RHTAPBUGS-1064](https://issues.redhat.com/browse/RHTAPBUGS-1064)

[RHTAPBUGS-1064](https://issues.redhat.com/browse/RHTAPBUGS-1064) is fixed. This PR is ready to be merged.

**Pull request merged**
