### PR TITLE
Add IntegrationTestScenario for api-frontend

### PR DESCRIPTION
**Pull request by fhlavac**
Add IntegrationTestScenario for api-frontend

### CODE REVIEW

**Review by ernesgonzalez33 — CHANGES_REQUESTED** [review]
@fhlavac you need to run the `build-manifests.sh` script

**Comment by fhlavac** [comment]
@ernesgonzalez33 running it looks to be removing a lot of files, is that correct?

**Comment by ernesgonzalez33** [comment]
@fhlavac no. That's not correct. I think this happens when kustomize is not installed. There is a script in this same repo to install it

**Comment by fhlavac** [comment]
@ernesgonzalez33 ahh, I missed that. Thank you!

**Review by ernesgonzalez33 — APPROVED** [review]

**Pull request merged**
