### PR TITLE
centos-bootc: Attempt to sync c10s with c9s

### PR DESCRIPTION
**Pull request by cgwalters**
xref https://gitlab.com/redhat/centos-stream/containers/bootc/-/issues/292

I just copy-pasted the current c9s config and did s/c9s/c10s/, hope that works.

### CODE REVIEW

**Review by ernesgonzalez33 — CHANGES_REQUESTED** [review]
I think you are missing running `build-manifests.sh` because I don't see the image repository manifest in the `auto-generated` folder

**Comment by lmilbaum** [comment]
I wasn't aware of this PR. The changes were already landed in separate PRs.

**Comment by ernesgonzalez33** [comment]
@lmilbaum should we close it then?

**Comment by arewm** [comment]
Closing this PR. Please reopen it if needed.

**Pull request closed without merging**
