### PR TITLE
chore(RHTAPREL-722): migrate acm prod RPAs

### PR DESCRIPTION
**Pull request by happybhati**
This commit removes RPA under rh-managed-red-hat-acm-tenant.   
And now available [here ](https://gitlab.cee.redhat.com/releng/konflux-release-data/-/tree/main/config/MS/ReleasePlanAdmission/crt-redhat-acm?ref_type=heads)
This is done as part of RPA migration Ticket: https://issues.redhat.com/browse/RHTAPREL-746

Signed-off-by: Happy Bhati hbhati@redhat.com

### CODE REVIEW

**Comment by happybhati** [comment]
@scoheb  PTAL, Thanks :)

**Comment by scoheb** [comment]
this PR should also possibly include a SA and RemoteSecret based on discussion here: https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/79#note_8625802

**Comment by happybhati** [comment]
> this PR should also possibly include a SA and RemoteSecret based on the discussion here: https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/79#note_8625802

@scoheb I have added SA and Sec in separate PR #212

**Comment by happybhati** [comment]
@davidmogar  please review/merge this whenever you get a chance.

**Comment by ralphbean** [comment]
@happybhati this needs a rebase on `main` and merge conflict resolution now.

**Review by ralphbean — APPROVED** [review]

**Pull request merged**
