### PR TITLE
Integration Tests

### PR DESCRIPTION
**Pull request by dscervantes**
Integration Tests

### CODE REVIEW

**Comment by dscervantes** [comment]
@scoheb @gbenhaim Would you be able to review this for me

**Comment by scoheb** [comment]
you need to run `build-manifests.sh` first before creating PR.

**Comment by dscervantes** [comment]
@scoheb Is this what it should output or does my namespace name should be the same one from this:
https://console.redhat.com/preview/application-pipeline/workspaces/rhtap-hcc-pipeline/applications/insights-ingress-go


 Error: accumulating resources: accumulation err='accumulating resources from 'integration_test_scenario.yaml': evalsymlink failure on '/home/dcervantes/Documents/tenants-config/cluster/stone-prd-rh01/tenants/rhtap-insightsingress-tenant/integration_test_scenario.yaml' : lstat /home/dcervantes/Documents/tenants-config/cluster/stone-prd-rh01/tenants/rhtap-insightsingress-tenant/integration_test_scenario.yaml: no such file or directory': evalsymlink failure on '/home/dcervantes/Documents/tenants-config/cluster/stone-prd-rh01/tenants/rhtap-insightsingress-tenant/integration_test_scenario.yaml' : lstat /home/dcervantes/Documents/tenants-config/cluster/stone-prd-rh01/tenants/rhtap-insightsingress-tenant/integration_test_scenario.yaml: no such file or directory
failed to build cluster/stone-prd-rh01/tenants/rhtap-insightsingress-tenant

**Comment by scoheb** [comment]
The final name has dashes in it.

**Pull request merged**
