### PR TITLE
Add RHDH Orchestrator operator release plan to orchestrator-releng-tenant

### PR DESCRIPTION
**Pull request by jordigilh**
@rgolangh @ralphbean  PTAL.

### CODE REVIEW

**Comment by ralphbean** [comment]
@jordigilh ok, after you add the files to the `cluster/` dir, you need to locally run `./build-manifests.sh` and commit the output of that also and include it here.

**Comment by ralphbean** [comment]
Oh, and the `kustomization.yaml` file **must** be in the root of the `cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/` dir. It cannot be in that `operator/` dir.

**Comment by jordigilh** [comment]
> Oh, and the `kustomization.yaml` file **must** be in the root of the `cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/` dir. It cannot be in that `operator/` dir.

Output is:
```
$> ./build-manifests.sh
Checking directory cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant
Checking directory cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant
Checking directory cluster/stone-prd-rh01/managed/rhtap-releng-tenant
Checking directory cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant
Checking directory cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant
Checking directory cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant
Checking directory cluster/stone-prd-rh01/tenants/konflux-console-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-devprod-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-ccx-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-trex-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-integration-tenant
Checking directory cluster/stone-prd-rh01/tenants/centos-bootc-tenant
Checking directory cluster/stone-prd-rh01/tenants/maestro-rhtap-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-subs-watch-tenant
Checking directory cluster/stone-prd-rh01/tenants/konflux-build-pipeli-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhbk-release-tenant
Checking directory cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-hms-tenant
Checking directory cluster/stone-prd-rh01/tenants/sfo-security-tenant
Checking directory cluster/stone-prd-rh01/tenants/trusted-content-tenant
Checking directory cluster/stone-prd-rh01/tenants/hcc-notifications-tenant
Checking directory cluster/stone-prd-rh01/tenants/crt-nshift-lightspeed-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-spi-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-build-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-acs-tenant
Checking directory cluster/stone-prd-rh01/tenants/assisted-installer-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-has-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-gitops-tenant
Checking directory cluster/stone-prd-rh01/tenants/konflux-mintmaker-tenant
Checking directory cluster/stone-prd-rh01/tenants/ergonzale-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-migration-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtas-tenant
Checking directory cluster/stone-prd-rh01/tenants/insights-runtimes-tenant
Checking directory cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant
Checking directory cluster/stone-prd-rh01/tenants/tekton-ecosystem-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-contract-tenant
Checking directory cluster/stone-prd-rh01/tenants/crt-nshift-appliance-tenant
Checking directory cluster/stone-prd-rh01/tenants/gbenhaim-tenant
Checking directory cluster/stone-prd-rh01/tenants/rh-terraform-tenant
Checking directory cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant
Checking directory cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant
Checking directory cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant
Checking directory cluster/stone-prd-rh01/tenants/awood1-tenant
Checking directory cluster/stone-prd-rh01/tenants/hcc-devprod-tenant
Checking directory cluster/stone-prd-rh01/tenants/konflux-infra-tenant
Checking directory cluster/stone-prd-rh01/tenants/ocm-cli-clients-tenant

```

**Comment by jordigilh** [comment]
> Oh, and the `kustomization.yaml` file **must** be in the root of the `cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/` dir. It cannot be in that `operator/` dir.

I was following the example from the multiarch-tuning-ope-tenant:
https://github.com/redhat-appstudio/tenants-config/blob/main/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/operator/kustomization.yaml

Is it wrong then?

**Comment by jordigilh** [comment]
> > Oh, and the `kustomization.yaml` file **must** be in the root of the `cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/` dir. It cannot be in that `operator/` dir.
> 
> I was following the example from the multiarch-tuning-ope-tenant: https://github.com/redhat-appstudio/tenants-config/blob/main/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/operator/kustomization.yaml
> 
> Is it wrong then?

If it's wrong, I'll need to have @rgolangh's #365 merged before mine to avoid merge conflict.

**Comment by ralphbean** [comment]
OK, https://github.com/redhat-appstudio/tenants-config/pull/365 is merged now.

**Comment by ralphbean** [comment]
Ah, the difference for multiarch tuning operator is in their base kustomization file. See how it explicitly references their `operator` directory? cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/kustomization.yaml

**Comment by jordigilh** [comment]
@ralphbean whenever you have spare time, can you take a look at this PR?

**Review by ralphbean — APPROVED** [review]

**Pull request merged**
